# Name for reference
name = "demo site"
# The base url of the site
base_url = "localhost"
# extra url aliases
aliases = ["local", "127.0.0.1"]
# where the static files are, {pwd} expands to the working directory, but best to use fully qualified if you can
root_dir = "{pwd}/demo_site" 
# your index document
index = "index.gemini"
# location of your certificate, best to use fully qualified if you can
fullchain = "certs/cert.pem"
private_key = "certs/privkey.pem"
# the port number to run on
port = 1965
